// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDpS3IbiGMQ4calwkhv3Cm1P5PwWcaKSk',
    appId: '1:254166081597:web:885079d82f1d34f1060a54',
    messagingSenderId: '254166081597',
    projectId: 'inkombe-12bb2',
    authDomain: 'inkombe-12bb2.firebaseapp.com',
    storageBucket: 'inkombe-12bb2.appspot.com',
    measurementId: 'G-EHX3XJ979D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUh0w-4sMd1q3usEBUuuckoA91FCPkm4',
    appId: '1:254166081597:android:82fef7808dd306b8060a54',
    messagingSenderId: '254166081597',
    projectId: 'inkombe-12bb2',
    storageBucket: 'inkombe-12bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX4Y4N8w4oJ2kt9RXHlawu0neebK3SEfk',
    appId: '1:254166081597:ios:d3bbcaa86cb8a47b060a54',
    messagingSenderId: '254166081597',
    projectId: 'inkombe-12bb2',
    storageBucket: 'inkombe-12bb2.appspot.com',
    iosBundleId: 'com.example.inkombeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX4Y4N8w4oJ2kt9RXHlawu0neebK3SEfk',
    appId: '1:254166081597:ios:d3bbcaa86cb8a47b060a54',
    messagingSenderId: '254166081597',
    projectId: 'inkombe-12bb2',
    storageBucket: 'inkombe-12bb2.appspot.com',
    iosBundleId: 'com.example.inkombeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDpS3IbiGMQ4calwkhv3Cm1P5PwWcaKSk',
    appId: '1:254166081597:web:b269c775b256b17b060a54',
    messagingSenderId: '254166081597',
    projectId: 'inkombe-12bb2',
    authDomain: 'inkombe-12bb2.firebaseapp.com',
    storageBucket: 'inkombe-12bb2.appspot.com',
    measurementId: 'G-Z052VV70M0',
  );
}
